### ISSUE TITLE
Error messages not returned in JSON response

### ISSUE THREAD

**Issue by layerzerolabs** [atlantishealthcare/swagger-model-validator#20] opened 2015-01-30 16:19 UTC
Hi,

I'm getting this kind of thing returned when I validate data against a model. Do I have to define my own error messages? From the Readme it looks like you can just use it out of the box.
```
{
  "valid": false,
  "errorCount": 1,
  "errors": [
    {}
  ]
}
```
Cheers

Naomi

**Comment by brodyd** [comment] 2015-02-01 21:02
You should get error messages in the errors array.  Any chance you can supply a sample of the data and the model?

**Comment by layerzerolabs** [comment] 2015-02-02 21:06
Here's the model:

```
{
      "id":"Reading",
      "required": ["sensor_name", "reading_time", "reading_value"],
      "properties": {
         "sensor_name": {
            "type": "string",
            "description": "Source of the message (e.g. 'Water Temperature', or 'system' if it is a system message)",
         }, 
         "reading_time": {
            "type": "string",
            "format": "date-time",
            "description": "Date and time the message was created"
         }, 
         "reading_value": {
            "type": "string",
            "description": "Content of the message (e.g. '22.6' or 'Reset triggered')"
         }
      }
   }
```
I would expect that if any of the fields are missing then I would get a message saying that they are required. But with data like this:
```
{'foo': 'bar'}
```
I get a error count of 3, with 3 empty error objects. With data like this:
```
{'sensor_name': 'light', 'reading_time': 'this-is-not-a-date', 'reading_value': '27'
```
I would expect an error message about an invalid date. Instead I just get an error count of 1, and 1 empty error object.

**Comment by brodyd** [comment] 2015-02-02 22:47
I have created the following test.

```
var model = {
            "id":"Reading",
            "required": ["sensor_name", "reading_time", "reading_value"],
            "properties": {
                "sensor_name": {
                    "type": "string",
                    "description": "Source of the message (e.g. 'Water Temperature', or 'system' if it is a system message)"
                },
                "reading_time": {
                    "type": "string",
                    "format": "date-time",
                    "description": "Date and time the message was created"
                },
                "reading_value": {
                    "type": "string",
                    "description": "Content of the message (e.g. '22.6' or 'Reset triggered')"
                }
            }
        };

        var data = {'sensor_name': 'light', 'reading_time': 'this-is-not-a-date', 'reading_value': '27'};

        validator = new Validator();
        validator.addFieldValidator("testModel", "id", function(name, value) {
            if(value === 34) {
                return new Error("Value Cannot be 34");
            }

            return null;
        });
        var result = validator.validate(data, model);

        test.ok(!result.valid);
        test.ok(result.errorCount === 1);
        test.ok(result.errors[0].message = "reading_time (this-is-not-a-date) is not a type of date-time");
```
This test is passing.  Could you please send me the validate call from your code.  
Please note that I am calling the validate method directly to make this test which changes some of the model behaviour (mainly we retrieve the actual model from the swagger client if we are passed a string instead of a model object - we assume a string is a name and anything else is a model)

**Comment by brodyd** [comment] 2015-02-02 22:54
Also could you tell me the error that you get if an actual require field is missing?

**Comment by brodyd** [comment] 2015-02-02 23:20
One last question. Are you running in Node or in a browser?  I think the way I create an error is node specific and might not work in a browser.

**Comment by layerzerolabs** [comment] 2015-02-03 09:33
It's running in node.
I have this code at the top of the file:
```
var SwaggerValidator = require('swagger-model-validator'),
   validator = new SwaggerValidator(swagger);

```
Then i define a function for posting data
```
var postReading = {
	'spec': {
        "description" : "Post a reading in a single category",
	"path" : "/todmorden",
	"notes" : "Records data in specified category (sensor or message type).\
 Date is accepted in local time.",
        "method": "POST",
        "parameters" : [{
	        "paramType": "body",
		    "name": "reading",
		    "required": true,
		    "type": "Reading",
		    "description": "Reading"
         }],
	    "errorResponses" : [
		    swagger.errors.invalid('date'), 
	    ],
     
	    "nickname" : "postReading"
	},
    action:  function (request, response) { 
        var validation = swagger.validateModel('Reading', request.body);
        if (!validation.valid) {
            return response.send(validation);
        }
        dataAccess.createReading(request.body, function (err){
          if (err){
            console.log('Can\'t create reading: '+err.message);
            response.status(400);
            response.send(err);
          } else {
            response.status(201);
            response.send({success: true});
          }
        });
    }
};
```

and then it all gets registered to swagger
```
swagger.addModels(require('./models')).addPost(postReading);
```

Hope that helps - let me know if you could use any more information. Thanks!

**Comment by brodyd** [comment] 2015-02-04 22:07
The problem is with extracting the error messages.  It appears that whatever does this need to explicitly get the Error messages.  So it is correctly returning the error object except that it has no properties when it it turned into JSON.  The validator is designed to return the errors to you directly so some post-processing is required to turn these into usable messages.

We use this function and pass in the error array.

```
function generateErrorMessages(response, errors) {
    var errorMessages = [];
    for (index in errors) {
        errorMessages.push(errors[index].message);
    }
    res.status(404).json({ errors: errorMessages });
}
```
So we'd call this with
```
return generateErrorMessages(res, errors) and it would call the response object for us.

**Comment by brodyd** [comment] 2015-02-04 22:11
What would like us to do about this?  Its really an issue with Error to JSON which is outside the scope of the validator.
We can: 
1. Stop sending the whole error and simple return an array of message strings
2. Keep sending entire error arrays and provide a method to return them as JSON better
3. Create a method on the validator that will send a response for you if validation fails.

I'll close this shortly - But there is not much I can do in the validator about Error to JSON formatting.

**Comment by brodyd** [comment] 2015-02-04 22:57
I am about to pop out a quick fix for your issue. See #23 for more details.

Use the following 
```
return response.status(404).send({ valid: false, 
                                   errorCount: validation.errorCount, 
                                   errors: validation.GetFormattedErrors() });
```

**Comment by layerzerolabs** [comment] 2015-02-05 14:52
Well, that is good service! :+1: 

Apologies for blaming your validator for what turned out to be a node/javascript issue that I was too much of a n00b to be aware of!

Sounds like the new methods are a good idea nonetheless. I'll certainly try them out. Thanks

**Comment by layerzerolabs** [comment] 2015-02-05 20:43
I've tried out the new functions ... GetErrorMessages works well but GetFormattedErrors was still returning empty objects (but in quotes ...)

I've edited the function so that it works for me, and issued a pull request.

**Comment by brodyd** [comment] 2015-02-08 19:53
The Pull Request has been merged - Many Thanks.

**Closed by brodyd** 2015-02-08 19:53 UTC
Labels: enhancement, question
